[[headers]]
  for = "*.js"
  [headers.values]
    Content-Type = "application/javascript"

[[headers]]
  for = "*.jsx"
  [headers.values]
    Content-Type = "application/javascript"

[build]
  command = "npm run build"
  publish = "dist"

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
```

Save it (Ctrl+S), then back in Command Prompt run:
```
git add .
git commit -m "Add netlify config"
git push 
